spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_test?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${THE_ONLY_ONE_KEY}
      chat:
#        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
#        base-url: https://api.cerebras.ai/
        base-url: https://openrouter.ai/api
        api-key: ${THE_ONLY_ONE_KEY}
        options:
#          model: gemini-2.5-flash-lite
#          model: gpt-oss-120b
          model: openrouter/free
#  ai:
#    google:
#      genai:
#        api-key: ${GOOGLE_AI_API_KEY}
#        chat:
#          options:
#            model: gemma-3-27b-it
##            model: gemini-2.5-flash
##            model: gemini-2.5-flash-lite
server:
  port: 8091
